name: Working Directory Shell Discover
on: [push]

jobs:
  discover-working-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory and print files
        run: |
          pwd
      - name: List Files
        run:  |
         ls -a
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
  discover-working-dir-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory and print files
        run: |
         Get-Location
      - name: List Files
        run:  |
         dir
         echo $env:GITHUB_SHA
         echo $env:GITHUB_REPOSITORY
         echo $env:GITHUB_WORKSPACE
                
